### ISSUE TITLE
Add trolleybus/tram placemarks to map

### ISSUE THREAD

**Issue by a-chabin** [ekaterinburgdev/transport#1]
Add test placemarks from [ettu.ru](http://www.ettu.ru) to [transport.ekaterinburg.io/map](https://transport.ekaterinburg.io/map)

- [x] Output routes
- [x] Show icon 
   - [x] Transport icon
   - [x] Show arrow
   - [x] Smooth moving
- [x] Autoupdate every 15 seconds

Temporary API endpoints:
- Transport coords
http://map.ettu.ru/api/v2/troll/boards/?apiKey=111&order=1
- Routes
http://map.ettu.ru/api/v2/troll/routes/?apiKey=111
- Stations with names, coords and ids
http://map.ettu.ru/api/v2/troll/stations/?apiKey=111&order=1
- All points of routes (not only stations)
http://map.ettu.ru/api/v2/troll/points/?apiKey=111&order=1

[![image](https://user-images.githubusercontent.com/22644149/193648347-26e5c6ba-e1bf-4912-a02b-dbe49cab4c2e.png)](https://yandex.ru/maps/54/yekaterinburg/stops/stop__9810883/?ll=60.610616%2C56.838472&tab=overview&z=18)

**Comment by hiba9201** [comment]
Allorigins caches requests which prevents update of transport positions on a map. Found fork of allorigins but with extra options such as disable cache: https://allorigins.hexlet.app/raw?disableCache=true&url=

**Comment by hiba9201** [comment]
Deleted markers clusterization from the list as I think it is a separate task. This one is already big enough

**Comment by a-chabin** [comment]
Done 
#2
