### ISSUE TITLE
Add current location placemark

### ISSUE THREAD

**Issue by a-chabin** [ekaterinburgdev/transport#4]
Add current location placemark

![image](https://user-images.githubusercontent.com/22644149/201540645-0c8b40af-29f2-483e-8d24-a1e49a509d8e.png)

**Comment by Omelekhin** [comment]
> Add current location placemark

"Вы здесь" has too thin white stroke. Can you make it a little bit thicker?

**Comment by hiba9201** [comment]
@tramakarov Could you update the design, please?
> "Вы здесь" has too thin white stroke. Can you make it a little bit thicker?

**Comment by hiba9201** [comment]
Had a talk with Egor. Right now this design looks like this
<img width="359" alt="image" src="https://user-images.githubusercontent.com/1540864/202843381-57eabac2-8c9f-442e-83f8-e5f1f08a66ba.png">

**Comment by tramakarov** [comment]
We discussed with @Omelekhin that it's better to uce place marker icon not icon with man. And about text under the icon -- let's create two versions: with and without this text
![image](https://user-images.githubusercontent.com/47551718/202847751-8840973d-e9c3-4bd5-92cf-0bfae04bd2a4.png)

**Comment by a-chabin** [comment]
@tramakarov
